name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    environment:
      name: testing
    env:
      DATABASE_HOSTNAME = ${{DATABASE_HOSTNAME}}
      DATABASE_PORT = ${{DATABASE_PORT}}
      DATABASE_PASSWORD = ${{DATABASE_PASSWORD}}
      DATABASE_NAME = ${{DATABASE_NAME}}
      DATABASE_USERNAME = ${{DATABASE_USERNAME}}
      SECRET_KEY = ${{SECRET_KEY}}
      ALGORITHM = ${{ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES = ${{ACCESS_TOKEN_EXPIRE_MINUTES}}

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v5
      - name: installing python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: upgrading pip
        run: python -m pip install --upgrade pip
      - name: installing requirements
        run: pip install -r requirements.txt

      - name: running tests with pytest
        run: |
          pip install pytest
          pytest


