name: Build and Dploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v5
      - name: installing python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: upgrading pip
        run: python -m pip install --upgrade pip
      - name: installing requirements
        run: pip install -r requirements.txt


